version: "3.7"
services:
  drone-service:
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://postgres_db:5432/drone_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=root
    depends_on:
      - postgres_db
  postgres_db:
    image: "postgres:14-alpine"
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: drone_db
    volumes:
      - postgres:/var/lib/postgresql/data
  pgadmin:
    image: "dpage/pgadmin4:latest"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    depends_on:
      - postgres_db
    volumes:
      - pgadmin:/var/lib/pgadmin
volumes:
  postgres:
  pgadmin: