server:
  port: 9090
spring:
  main:
    web-application-type: reactive
  application:
    name: API-CLOUD-GATEWAY
  cloud:
    gateway:
      routes:
        - id: CLIENT-SERVICE
          uri: lb://client:8080
          predicates:
            - Path=/api/client/**
        - id: MEDICATION-SERVICE
          uri: lb://medication:8081
          predicates:
            - Path=/api/medication/**
        - id: DRONE-SERVICE
          uri: lb://drone:8082
          predicates:
            - Path=/api/drone/**
        - id: NOTIFICATION-SERVICE
          uri: lb://notification:8084
          predicates:
            - Path=/api/notification/**
        - id: SHIPMENT-SERVICE
          uri: lb://shipment:8083
          predicates:
            -Path=/api/shipment/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-discovery:8761/eureka/