server:
  port: 9090
spring:
  main:
    web-application-type: reactive
  application:
    name: API-CLOUD-GATEWAY
  cloud:
    gateway:
      routes:
        - id: CLIENT-SERVICE
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/api/client/**
        - id: MEDICATION-SERVICE
          uri: lb://MEDICATION-SERVICE
          predicates:
            - Path=/api/medication/**
        - id: DRONE-SERVICE
          uri: lb://DRONE-SERVICE
          predicates:
            - Path=/api/drone/**
        - id: NOTIFICATION-SERVICE
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notification/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/