server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost

spring:
  application:
    name: SERVICE-DISCOVERY


logging:
  level:
    com.digiconnect: debug
    root: info