spring:
  application:
    name: DRONE-PROJECT
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  jpa:
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB

logging:
  level:
    org.springframework.web: ERROR
    com: DEBUG
