server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/medication_db
    username: postgres
    password: root
    initialization-mode: always
user-defined:
  root:
    folder: medication-images