server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/medication_db
    username: postgres
    password: root
    initialization-mode: always
  rabbitmq:
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
user-defined:
  root:
    folder: medication-images
client:
  url: http://localhost:8080/
